[General]
codecs-profiles-selected=Audio - MP3
filedialog-path=@Variant(\0\0\0\x11\0\0\0-file:///home/arturl/2023-12-27%2017-18-52.mkv)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc0\0\0\0*\0\0\a\x7f\0\0\x4\x37\0\0\x3\xc1\0\0\0+\0\0\a~\0\0\x4\x36\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc1\0\0\0+\0\0\a~\0\0\x4\x36)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(958 945)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
netMRL=
size=@Size(518 400)

[RecentsMRL]
list=file:///home/arturl/Demonstra%C3%A7%C3%A3o.mkv, file:///home/arturl/2024-01-24%2019-12-46.mkv, file:///home/arturl/2024-01-24%2019-10-42.mkv, file:///home/arturl/2024-01-24%2019-03-17.mkv, file:///home/arturl/2024-01-24%2018-28-59.mkv, file:///home/arturl/2024-01-24%2018-27-12.mkv, file:///home/arturl/2024-01-24%2017-52-20.mkv, file:///home/arturl/2023-12-27%2017-18-52.mkv, file:///home/arturl/Downloads/goncalo_final.mp4
times=118983, 0, 0, 34015, 139423, 0, 0, 0, 197846
