ipc = off

preload = /home/arturl/Downloads/wallpaperflare.com_wallpaper.jpg

wallpaper = eDP-1, /home/arturl/Downloads/wallpaperflare.com_wallpaper.jpg
wallpaper = HDMI-A-1, /home/arturl/Downloads/wallpaperflare.com_wallpaper.jpg
