theme = "kanagawa-dragon"

[editor]
line-number = "relative"
mouse = false
auto-pairs = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
